### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by hilliaho** [trickwide/personal-finance-tracker#1]
Käyttöohjeet README:ssa ovat selkeät ja sain niiden avulla sovelluksen toimimaan ilman vaikeuksia.

Kaiken kaikkiaan käyttökokemus on toimiva ja oli vaikea löytää parannettavaa jos ottaa huomioon READMEssa kerrotut asiat, mitä aiot joka tapauksessa vielä tehdä, mutta kerron nyt pari asiaa mihin kiinnitin huomiota.

1. Tämä on ehkä makuasia, mutta itse pidän erikoismerkkivaatimusta salasanaan vähän hankalana ja sen sijaan voisi vaikka pidentää salasanan vähimmäispituusvaatimusta 10 merkkiin.

2. On vähän epätavanomaista, että kirjautuneena käyttäjänä pystyy rekisteröityä uudestaan ja kirjautua sisään toisella käyttäjällä ilman, että pitää ensin kirjautua ulos. Toisaalta en nyt tiedä onko siitä haittaakaan.

Sovellus on erittäin hyvässä vaiheessa. Kirjautuminen ja rekisteröityminen sovellukseen on tehty hyvin. Kirjautuneena käyttäjänä tietojen lisääminen toimii ja lisätyt tiedot tulevat näkyviin. Hyvää työtä!

Ohjelmakoodi on jaettu hyvin eri tiedostoihin ja on helppo lukea. Tietokannan rakenne näyttää myös hyvältä.

**Comment by trickwide** [comment]
Kiitos vertaisarvioinnista! Tuo 2. kohta on itseasiassa äärimmäisen hyvä nosto, joka ei ollut itselle edes tullut mieleen sovellusta testaillessa. Katsotaan minkälaisella viritelmällä lähden muutosta toteuttamaan 😁
