### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by ElisaMero** [trickwide/personal-finance-tracker#2]
Rekisteröityessä ei hyväksy käyttäjää ja salasanaa, vaikka ne olisi kirjoitettu oikein.  Submit jälkeen tulee 500 internal server error (Key error: csrf_tolken error). Kirjautuminen ja rekisteröityminen ei siis onnistu. 

Koodi näyttää kaikankaikkiaan siistiltä ja toiminnallisuudet kattavilta. Tietokantoja on hyvä määrä. Lisäksi rekisteröitymissivun ja kirjautumissivun ulkoasut ovat siistejä. Ehkä rekisteröitymissivustolla olevat salasanan ja käyttäjänimen ohjeet voisivat olla isommalla fontilla, jotta ne olisivat selkeämmät. 

Työ on hyvällä mallilla, kunhan kirjautumisbugit saa selvitettyä!

**Comment by trickwide** [comment]
CSRF-haavoittuvuudelta suojautuminen olikin sitten jättänyt tämän pienen, mutta merkittävästi sovelluksen käyttöä haittaavan bugin. CSRF-bugi on nyt korjattu, sovelluksen viimeisin versio puskettu repoon sekä varmistettu, että kaiken pitäisi toimia mallikkaasti. Ohjeiden fonttikoon testailut katson myöhemmin, kiitos paljon vertaisarvionnistasi 😄
